import type { Metadata } from "next";
import { Inclusive_Sans } from "@next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/layouts/header";
import ThemeProvider from "@/components/providers/theme-provider";
import Footer from "@/components/layouts/footer";

const icomoon = Inclusive_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-icomoon",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `poppins-thin h-screen bg-background font-icomoon flex flex-col`
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="h-screen overflow-y-auto bg-[url('/bg.jpg')] object-fill bg-cover bg-center bg-no-repeat">
            {children}
          </div>
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
